services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-agent-web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - DEBUG=True
    command: uvicorn app.core:app --host 0.0.0.0 --port 8000 --reload

  mongo:
    image: mongo:latest
    container_name: blog-agent-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: unless-stopped

volumes:
  mongo_data:
